# Generated by Django 5.1.7 on 2025-04-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
