# Generated by Django 3.2.25 on 2025-09-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20250925_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media/images/user.jpg', null=True, upload_to='profile/'),
        ),
    ]
