# Generated by Django 3.2.25 on 2025-10-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
