# Generated by Django 3.2.25 on 2025-10-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_delete_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
