# Generated by Django 3.2.25 on 2025-10-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
    ]
